baseURL = "https://adriantriks.xyz/"
languageCode = "en-us"
title = "Adrian Tricks & Alternative"
theme = "anatole"


#About me

[params]
title = "Adrian Tricks & Alternative"
author = "Adrian Candra Kusumah"
description = "Situs trik dan alternatif software untuk pc. Mulai dari Linux, aplikasi gratis, dll."
profilePicture = "images/Cool.png"
